# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.3'

gem 'bootsnap', require: false
gem 'date_validator', '~> 0.9.0'
gem 'devise', '~> 4.6.0'
gem 'jbuilder', '~> 2.0'
gem 'mysql2', '~> 0.5.0'
gem 'paperclip', '~> 5.1.0'
gem 'puma'
gem 'rails', '5.2.3'
gem 'rails-settings-cached', '~> 0.7.0'

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

group :test do
  gem 'capybara'
  gem 'coveralls', require: false
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
end

group :development do
  gem 'listen'
  gem 'rubocop-rails'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'web-console', '~> 3.7.0'
end

group :test, :development do
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end
